---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart traefik
  ansible.builtin.systemd:
    name: traefik
    state: restarted
  when: ansible_facts['service_mgr'] == 'systemd'

- name: restart traefik compose
  ansible.builtin.command: >-
    /usr/bin/docker compose -f {{ traefik_base_dir }}/docker-compose.yml
    --project-directory {{ traefik_base_dir }} restart
  args:
    chdir: "{{ traefik_base_dir }}"
  when: ansible_facts['service_mgr'] != 'systemd'
